In [53]:
import pandas as pd
from tqdm import tqdm
import string
tqdm.pandas()
import spacy
import numpy as np
from sentence_transformers import SentenceTransformer, util
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import BertTokenizer
import nltk
from nltk.corpus import stopwords
import string
import keras_nlp
import numpy as np

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [55]:
cd /content/drive/MyDrive/Hackathon

/content/drive/MyDrive/Hackathon

**IMPORTING PKL FILE OF EDITED CSV**

A column(embeddings) which was MiniLM embedding of information

In [56]:
df = pd.read_pickle("embeddings_new.pkl")

In [57]:
import ast

In [58]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [59]:
text="i am  poor farmer"

In [60]:
sentence_emb = model.encode([text], convert_to_tensor=True)

In [61]:
from sklearn.metrics.pairwise import cosine_similarity
import tensorflow as tf

def compare(sentence_emb,scheme_embedding):
  sentence_embedding_2d = sentence_emb.numpy().reshape(1, -1)
  scheme_embedding_2d = scheme_embedding.numpy().reshape(1, -1)
  # Calculate the cosine similarity
  similarity = cosine_similarity(sentence_embedding_2d, scheme_embedding_2d)
  return similarity.item()

In [62]:
def get_top_k(df, sentence_emb, compare_fn, emb_col="embeddings", k=5):
    # Apply the compare function to each embedding in the column
    df = df.copy()  # avoid modifying original
    df["similarity"] = df[emb_col].apply(lambda emb: compare_fn(sentence_emb, emb))
    # Sort by similarity in descending order
    top_k = df.sort_values("similarity", ascending=False).head(k)
    return top_k

In [63]:
get_top_k(df, sentence_emb,compare, emb_col="embeddings", k=5)

,scheme_name,details,benefits,documents,schemeCategory,tags,tokens,embeddings,similarity
381,Pradhan Mantri Kisan Samman Nidhi,Objective The scheme aims to supplement the fi...,Financial benefit of Rs. 6000 per annum per fa...,Indicative Documents Aadhaar Card Landholding ...,"Agriculture,Rural & Environment, Social welfar...","Farmers, Income Support, Agricultural Inputs, ...",Objective The scheme aims to supplement the fi...,"[tensor(-0.0379), tensor(0.0197), tensor(-0.12...",0.453740
33,Agri-Clinics And Agri-Business Centres Scheme,A welfare scheme by the Ministry of Agricultur...,Agri-Clinics - Agri-Clinics are envisaged to p...,1. Applicant Aadhaar Number. 2. Email ID. 3. L...,"Agriculture,Rural & Environment, Business & En...","Business, Entrepreneur, Student, Training, Agr...",A welfare scheme by the Ministry of Agricultur...,"[tensor(-0.0589), tensor(-0.0446), tensor(-0.0...",0.450001
297,National Livestock Mission: Establishment of E...,"The ""Establishment of Entrepreneurship for Bre...",Financial Assistance: One Time 50% capital sub...,A. Documents Related to Project Detailed proje...,"Business & Entrepreneurship, Agriculture,Rural...","Rural Poultry, Poultry Farming, Entrepreneursh...","The ""Establishment of Entrepreneurship for Bre...","[tensor(0.0191), tensor(-0.0911), tensor(-0.04...",0.432401
492,Sub-mission On Agriculture Mechanization,Agricultural machines take an important role t...,The stated objectives of the SMAM scheme are a...,For farmers Aadhar card - To identify the bene...,"Agriculture,Rural & Environment","Sub-Mission, Agriculture, Mechanization, SMAM",Agricultural machines take an important role t...,"[tensor(-0.0299), tensor(0.0364), tensor(-0.03...",0.429759
114,Establishment of Entrepreneur for Breed Develo...,"Launched in the Financial Year 2014-15, the sc...",CAPITAL SUBSIDY STRUCTURE Maximum capital subs...,A. Documents Related to Project Detailed proje...,"Agriculture,Rural & Environment","Entrepreneur, Breed, Investment, Subsidy, Shee...","Launched in the Financial Year 2014-15, the sc...","[tensor(0.0822), tensor(-0.0544), tensor(-0.03...",0.423692

In [64]:
def get_schemes(sentence_emb,df):
  return get_top_k(df, sentence_emb,compare, emb_col="embeddings", k=5)

In [71]:
data=get_schemes(sentence_emb,df)

In [72]:
output=data[["scheme_name","details","benefits","schemeCategory"]]

In [73]:
output

,scheme_name,details,benefits,schemeCategory
381,Pradhan Mantri Kisan Samman Nidhi,Objective The scheme aims to supplement the fi...,Financial benefit of Rs. 6000 per annum per fa...,"Agriculture,Rural & Environment, Social welfar..."
33,Agri-Clinics And Agri-Business Centres Scheme,A welfare scheme by the Ministry of Agricultur...,Agri-Clinics - Agri-Clinics are envisaged to p...,"Agriculture,Rural & Environment, Business & En..."
297,National Livestock Mission: Establishment of E...,"The ""Establishment of Entrepreneurship for Bre...",Financial Assistance: One Time 50% capital sub...,"Business & Entrepreneurship, Agriculture,Rural..."
492,Sub-mission On Agriculture Mechanization,Agricultural machines take an important role t...,The stated objectives of the SMAM scheme are a...,"Agriculture,Rural & Environment"
114,Establishment of Entrepreneur for Breed Develo...,"Launched in the Financial Year 2014-15, the sc...",CAPITAL SUBSIDY STRUCTURE Maximum capital subs...,"Agriculture,Rural & Environment"

In [74]:
null_embeddings_indices = df[df['embeddings'].isnull()].index.tolist()

In [75]:
null_embeddings_indices

[]

In [76]:

from google import genai

client = genai.Client(api_key="AIzaSyBiGcdP5rHCA6NWiDTrsTSv9ELnYvCznFA")

response = client.models.generate_content(
    model="gemini-2.5-flash", contents=f"""
this dataset have just 5 rows, display the schemes, followed by corresponding details, benefits,and documents required
{output}
only the info of this data should be given as output, nothing else
make it look easy to read for a normal person
"""
)
print(response.text)

Here's a breakdown of the schemes from your dataset:

---

### **1. Pradhan Mantri Kisan Samman Nidhi**

*   **Details:** This scheme aims to provide financial support to farmer families to help with their expenses.
*   **Benefits:** Farmers receive a financial benefit of ₹6,000 per year, given in three equal payments of ₹2,000 each, directly into their bank accounts.
*   **Category:** Agriculture, Rural & Environment, Social Welfare.

---

### **2. Agri-Clinics And Agri-Business Centres Scheme**

*   **Details:** A welfare scheme by the Ministry of Agriculture focused on setting up agri-clinics and agri-business centers.
*   **Benefits:**
    *   **Agri-Clinics:** Offer professional advice and services to farmers for improving crop production and increasing income.
    *   **Agri-Business Centres:** Provide commercial agricultural services like supplying quality inputs, custom hiring of farm equipment, and other support.
*   **Category:** Agriculture, Rural & Environment, Business & Entrepreneurship.

---

### **3. National Livestock Mission: Establishment of Entrepreneur for Breed Development of Poultry, Sheep, Goat & Pig including Feed and Fodder**

*   **Details:** This program, under the National Livestock Mission, focuses on promoting entrepreneurship for developing and improving breeds of poultry, sheep, goats, and pigs, along with support for feed and fodder production.
*   **Benefits:** Financial assistance is provided, including a one-time 50% capital subsidy (up to a certain limit) for establishing various related units like sheep/goat breeding farms, pig breeding farms, and poultry hatcheries.
*   **Category:** Business & Entrepreneurship, Agriculture, Rural & Environment.

---

### **4. Sub-mission On Agriculture Mechanization (SMAM)**

*   **Details:** This scheme recognizes the crucial role of agricultural machines in farming. It aims to increase the reach of farm mechanization to small and marginal farmers and regions where it's not widely used.
*   **Benefits:**
    *   Boost farm mechanization for all farmers.
    *   Provide financial support to buy agricultural machinery.
    *   Create hubs for custom hiring of farm machinery.
    *   Promote "Farm Mechanization" in areas where it's less common.
    *   Train and test agricultural machinery.
*   **Category:** Agriculture, Rural & Environment.

---

### **5. Establishment of Entrepreneur for Breed Development of Poultry, Sheep, Goat & Pig including Feed and Fodder**

*   **Details:** Launched in 2014-15, this scheme aims to support entrepreneurs involved in improving and developing breeds of poultry, sheep, goats, and pigs, including aspects of feed and fodder.
*   **Benefits:** Provides capital subsidy for setting up various units:
    *   Sheep & Goat Breeding Farm: 50% of the project cost, up to ₹50 lakhs.
    *   Pig Breeding Farm: 50% of the project cost, up to ₹30 lakhs.
    *   Poultry Parent Farm (for chicks): 50% of the project cost, up to ₹25 lakhs.
    *   Feed and Fodder Entrepreneurship: 50% of the project cost, up to ₹50 lakhs.
*   **Category:** Agriculture, Rural & Environment.